-- Run once in Supabase > SQL Editor. Safe to run again.
begin;
create table if not exists public.club_members (
 id bigint generated by default as identity primary key,
 name text not null check (length(btrim(name)) between 1 and 40)
);
create unique index if not exists club_members_name_unique on public.club_members(lower(btrim(name)));
create table if not exists public.club_albums (
 id bigint generated by default as identity primary key,
 member_id bigint not null references public.club_members(id),
 week date not null check (extract(isodow from week)=1),
 title text not null check (length(btrim(title)) between 1 and 120),
 artist text not null check (length(btrim(artist)) between 1 and 120),
 link text not null default '' check (length(link)<=2000 and (link='' or link ~ '^https?://[^/]+')),
 cover_url text not null default '' check (length(cover_url)<=2000 and (cover_url='' or cover_url ~ '^https://[^/]+')),
 spotify_url text not null default '' check (length(spotify_url)<=2000 and (spotify_url='' or spotify_url ~ '^https://open[.]spotify[.]com/')),
 deezer_url text not null default '' check (length(deezer_url)<=2000 and (deezer_url='' or deezer_url ~ '^https://www[.]deezer[.]com/')),
 unique(member_id,week)
);
create table if not exists public.club_ratings (
 album_id bigint not null references public.club_albums(id),
 member_id bigint not null references public.club_members(id),
 score integer not null check (score between 0 and 10),
 primary key(album_id,member_id)
);
insert into public.club_members(name) values ('Cédric'),('Côme'),('Issa') on conflict do nothing;

-- No passwords yet: this is an intentionally open club. Anyone with the site
-- can choose any profile. Only the dedicated function can delete a selected profile's own album.
alter table public.club_members enable row level security;
alter table public.club_albums enable row level security;
alter table public.club_ratings enable row level security;
revoke all on public.club_members,public.club_albums,public.club_ratings from anon,authenticated;
grant select,insert on public.club_members,public.club_albums,public.club_ratings to anon,authenticated;
grant update(score) on public.club_ratings to anon,authenticated;
grant usage,select on sequence public.club_members_id_seq,public.club_albums_id_seq to anon,authenticated;
drop policy if exists club_read_members on public.club_members;
create policy club_read_members on public.club_members for select to anon,authenticated using(true);
drop policy if exists club_add_members on public.club_members;
create policy club_add_members on public.club_members for insert to anon,authenticated with check(true);
drop policy if exists club_read_albums on public.club_albums;
create policy club_read_albums on public.club_albums for select to anon,authenticated using(true);
drop policy if exists club_add_albums on public.club_albums;
create policy club_add_albums on public.club_albums for insert to anon,authenticated with check(true);
drop policy if exists club_read_ratings on public.club_ratings;
create policy club_read_ratings on public.club_ratings for select to anon,authenticated using(true);
drop policy if exists club_add_ratings on public.club_ratings;
create policy club_add_ratings on public.club_ratings for insert to anon,authenticated with check(true);
drop policy if exists club_change_ratings on public.club_ratings;
create policy club_change_ratings on public.club_ratings for update to anon,authenticated using(true) with check(true);

create or replace function public.club_week(selected_week date) returns jsonb
language sql stable security invoker set search_path = '' as $$
 select jsonb_build_object(
 'members',(select coalesce(jsonb_agg(to_jsonb(m) order by m.id),'[]'::jsonb) from public.club_members m),
 'albums',(select coalesce(jsonb_agg(to_jsonb(a)||jsonb_build_object('ratings',
   (select coalesce(jsonb_agg(jsonb_build_object('member_id',r.member_id,'score',r.score) order by r.member_id),'[]'::jsonb)
    from public.club_ratings r where r.album_id=a.id)) order by a.member_id),'[]'::jsonb)
   from public.club_albums a where a.week=selected_week),
 'history',(select coalesce(jsonb_agg(to_jsonb(h) order by h.week desc),'[]'::jsonb) from (
   select a.week,count(distinct a.id) as album_count,count(r.score) as rating_count,round(avg(r.score),1) as average
   from public.club_albums a left join public.club_ratings r on r.album_id=a.id group by a.week
 ) h));
$$;
revoke all on function public.club_week(date) from public;
grant execute on function public.club_week(date) to anon,authenticated;
create or replace function public.club_rate(selected_album bigint, selected_member bigint, new_score integer)
returns void language sql security invoker set search_path = '' as $$
 insert into public.club_ratings(album_id,member_id,score) values(selected_album,selected_member,new_score)
 on conflict(album_id,member_id) do update set score=excluded.score;
$$;
revoke all on function public.club_rate(bigint,bigint,integer) from public;
grant execute on function public.club_rate(bigint,bigint,integer) to anon,authenticated;
commit;

-- Run in SQL Editor to add deletion without changing existing data.
begin;
create or replace function public.club_delete_album(selected_album bigint, selected_member bigint)
returns void language plpgsql security definer set search_path = '' as $$
declare proposer bigint;
begin
 select member_id into proposer from public.club_albums where id=selected_album for update;
 if not found then raise exception 'Cet album a déjà été supprimé.'; end if;
 if selected_member is null or proposer<>selected_member then
  raise exception 'Tu peux seulement supprimer tes propres propositions.' using errcode='42501';
 end if;
 delete from public.club_ratings where album_id=selected_album;
 delete from public.club_albums where id=selected_album;
end;
$$;
revoke all on function public.club_delete_album(bigint,bigint) from public;
grant execute on function public.club_delete_album(bigint,bigint) to anon,authenticated;
commit;
